onboarding = false

[keys]
# when you do `Ctrl+b+w` you can navigate using `k` and `j`
navigate_workspace_up = ["up", "k"]
navigate_workspace_down = ["down", "j"]

[ui]
# when you create a new workspace (via `Ctrl+b+N`) will prompt the workspace name
prompt_new_workspace_name = true
